### PR TITLE
r? ianbicking Fixes #2055 Add .png extension to the filename of the downloaded file.

### LINKED ISSUE #2055: Release 4.0 Deneb

### PR DESCRIPTION
**Pull request by fzzzy**

### CODE REVIEW

**Comment by ianb** [comment]
I thought the extension was automatically added?  At least currently this is used with `<a download={shot.filename}>` where I'm pretty sure the extension will be added.

**Comment by fzzzy** [comment]
I tested on mac and it was not added. Cosmin tested on windows and it is not. So I have no idea why it isn't getting added automatically?

**Comment by ianb** [comment]
Is this only with the download button during selection, or is it also on the download button in the shot page?  I thought we tested on the shot page, and this method will affect both locations.

**Comment by fzzzy** [comment]
Yes, it was for the download button during selection. You're right, the download button on the shot page adds png. It is probably better to put it in the filename getter rather than having multiple places in the code hardcode adding png, in case shots become capable of being saved in other formats at some point.

**Comment by ianb** [comment]
Note you don't need string interpolation once you remove the extension

**Comment by ianb** [comment]
Otherwise r+

**Pull request merged**
