### PR TITLE
add bright button a/b test

### PR DESCRIPTION
**Pull request by johngruen**
This actually fixes all of my elnath issues

### CODE REVIEW

**Comment by johngruen** [comment]
Fixes #2082
Fixes #1792 
Fixes #2064

**Comment by johngruen** [comment]
Also cleans up all the scss-lint warnings except the inline-selection page

**Comment by ianb** [comment]
I took a shot of [this page](https://github.com/mozilla-services/pageshot/issues/2120) and got this:

image

It didn't take the title of the page, and there's a big empty space to the left of the title.

In general I realize there's an elastic space to the left of the title, instead of the right.

Aha, looking more closely for some reason the extracted Open Graph title of the page is `mozilla/page-shot`, though that's not what it should be.  I'll open a separate bug for that (#2121).  Still the whitespace is a problem.

Responsive design mode in Firefox looks okay, in Chrome it doesn't work at all, though I'm going to assume that's a Chrome problem:

image

I assume it was your intention to change the color of all the buttons, but that's not what the test description describes:

image

My only blocking concern is the whitespace issue, though being clearer about the A/B test description would also be good.  The description is in `server/src/ab-tests.js`

**Comment by johngruen** [comment]
@ianb huh, yeah, i can change just the one button

also not sure what's going on with the responsive stuff, will investigate

**Comment by johngruen** [comment]
@ianb force pushed changes to iframe button colors and the broken title layout on the shot page. WRT responsive view might be nice to deploy this to stage to actually debug with mobile devices. I'm guessing (hoping) that there's a chrome bug happening.

**Comment by johngruen** [comment]
one sec...think i figured out the breakage

**Comment by ianb** [comment]
I'm still seeing the whitespace when the window is wide:

image

**Pull request merged**
